
services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - NAME=lol
      - USER=postgres
      - PASSWORD=postgres
      - HOST=127.0.0.1
      - PORT=5432
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank_history
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
