
services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/bank_history
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank_history
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
