name: CI/CD for Amvera

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bank_history
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Run pylint
        run: pylint visits/ --rcfile=.pylintrc
      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/bank_history
        run: python manage.py test visits

  deploy_production:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Deploy to Amvera
        env:
          AMVERA_TOKEN: ${{ secrets.AMVERA_TOKEN }}
        run: |
          python -c "
          import requests
          import os
          headers = {'Authorization': 'Bearer $AMVERA_TOKEN'}
          files = {'file': open('amvera.yml', 'rb')}
          response = requests.post('https://api.amvera.ru/projects/bank-history-prod/files', headers=headers, files=files)
          print(response.text)
          response = requests.post('https://api.amvera.ru/projects/bank-history-prod/build', headers=headers)
          print(response.text)
          "
      - name: Check deployment
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://bank-history-prod.<username>.amvera.io/visits/ | grep 200