name: CI/CD for Amvera

on:
  push:
    branches: [ master ]

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check deployment
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://bank-history-prod.<username>.amvera.io/visits/ | grep 200